name: "Stub Pro Crate"
description: "Ensures ghost-pro stub crate exists for open-source/CI builds"

runs:
  using: composite
  steps:
    - name: Verify pro stub exists
      shell: bash
      run: |
        if [ -f pro/Cargo.toml ] && [ -f pro/src/lib.rs ]; then
          echo "✓ ghost-pro stub found in repo"
        else
          echo "✗ ghost-pro stub files missing — this should not happen"
          echo "  The stub files should be committed to the repo."
          exit 1
        fi
