name: "Stub Pro Crate"
description: "Creates a stub ghost-pro crate when the private submodule is unavailable (CI/open-source builds)"

runs:
  using: composite
  steps:
    - name: Stub pro crate if submodule unavailable
      shell: bash
      run: |
        if [ -f pro/Cargo.toml ]; then
          echo "✓ ghost-pro submodule found, skipping stub"
          exit 0
        fi

        echo "→ Creating ghost-pro stub for open-source build..."
        mkdir -p pro/src/encryption pro/src/sync

        cat > pro/Cargo.toml << 'EOF'
        [package]
        name = "ghost-pro"
        version = "0.1.0"
        edition = "2021"
        publish = false

        [dependencies]
        serde = { version = "1", features = ["derive"] }
        serde_json = "1"
        tokio = { version = "1", features = ["full"] }
        tracing = "0.1"
        thiserror = "2"
        anyhow = "1"
        EOF

        cat > pro/src/lib.rs << 'EOF'
        pub mod encryption;
        pub mod sync;

        pub fn is_licensed() -> bool {
            false
        }

        pub fn version() -> &'static str {
            "0.0.0-stub"
        }

        pub async fn initialize() -> anyhow::Result<()> {
            Ok(())
        }
        EOF

        cat > pro/src/encryption/mod.rs << 'EOF'
        pub struct EncryptionEngine;
        impl EncryptionEngine {
            pub fn new() -> Self {
                Self
            }
        }
        EOF

        cat > pro/src/sync/mod.rs << 'EOF'
        pub struct SyncEngine;
        impl SyncEngine {
            pub fn new() -> Self {
                Self
            }
        }
        EOF

        echo "✓ ghost-pro stub created"
